[package]
name = "capy_macros"
version = "0.1.0-alpha.1"
edition = "2024"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
litrs = "0.4.0"
quote = "1.0.31"
