[package]
name = "topo"
version = "0.1.0-alpha.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.7.1"

[dev-dependencies]
itertools = "0.14.0"
